import { useState, useMemo } from 'react';
import { 
  Plus, 
  Pencil, 
  Trash2, 
  Phone, 
  CalendarPlus,
  MoreHorizontal,
  Filter
} from 'lucide-react';
import { AppLayout } from '@/components/layout/AppLayout';
import { DataTable, Column } from '@/components/common/DataTable';
import { CompactModal } from '@/components/common/CompactModal';
import { ConfirmDialog } from '@/components/common/ConfirmDialog';
import { StatusBadge } from '@/components/common/StatusBadge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { Calendar } from '@/components/ui/calendar';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/contexts/AuthContext';
import { Lead, LeadSource, LeadWithDetails } from '@/types';
import { 
  mockLeads, 
  mockAccounts, 
  mockUsers, 
  mockLeadStages, 
  mockLeadStatuses,
  getLeadWithDetails 
} from '@/lib/mockData';
import { formatCurrency, formatDate } from '@/lib/formatters';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';

const leadSources: LeadSource[] = ['Website', 'LinkedIn', 'Intern', 'Employee', 'Referral'];

export default function Leads() {
  const { toast } = useToast();
  const { hasPermission, currentUser } = useAuth();
  const [leads, setLeads] = useState<Lead[]>(mockLeads);
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [stageFilter, setStageFilter] = useState<string>('all');
  const [sourceFilter, setSourceFilter] = useState<string>('all');
  const [sortKey, setSortKey] = useState<string>('lead_date');
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc');
  const [editModalOpen, setEditModalOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);
  const [formData, setFormData] = useState<Partial<Lead>>({});
  const [selectedIds, setSelectedIds] = useState<(string | number)[]>([]);

  const limit = 10;

  const leadsWithDetails = useMemo(() => {
    return leads.map(lead => getLeadWithDetails(lead));
  }, [leads]);

  const filteredData = useMemo(() => {
    let result = [...leadsWithDetails];
    
    if (search) {
      const q = search.toLowerCase();
      result = result.filter(l => 
        l.account_name.toLowerCase().includes(q) ||
        l.products_interested.toLowerCase().includes(q) ||
        l.remarks.toLowerCase().includes(q)
      );
    }
    
    if (stageFilter !== 'all') {
      result = result.filter(l => l.stage_id === Number(stageFilter));
    }
    
    if (sourceFilter !== 'all') {
      result = result.filter(l => l.lead_source === sourceFilter);
    }
    
    result.sort((a, b) => {
      const aVal = a[sortKey as keyof LeadWithDetails];
      const bVal = b[sortKey as keyof LeadWithDetails];
      const modifier = sortDirection === 'asc' ? 1 : -1;
      if (typeof aVal === 'string' && typeof bVal === 'string') {
        return aVal.localeCompare(bVal) * modifier;
      }
      return ((aVal as number) - (bVal as number)) * modifier;
    });
    
    return result;
  }, [leadsWithDetails, search, stageFilter, sourceFilter, sortKey, sortDirection]);

  const paginatedData = filteredData.slice((page - 1) * limit, page * limit);

  const statusesForStage = useMemo(() => {
    if (!formData.stage_id) return mockLeadStatuses;
    return mockLeadStatuses.filter(s => s.stage_id === formData.stage_id);
  }, [formData.stage_id]);

  const columns: Column<LeadWithDetails>[] = [
    { key: 'lead_id', header: 'ID', className: 'w-14' },
    { 
      key: 'lead_date', 
      header: 'Date', 
      sortable: true,
      render: (row) => formatDate(row.lead_date)
    },
    { 
      key: 'account_name', 
      header: 'Account', 
      sortable: true,
      render: (row) => <span className="font-medium">{row.account_name}</span>
    },
    { key: 'lead_source', header: 'Source' },
    { key: 'generated_by_name', header: 'Generated By' },
    { key: 'telecaller_name', header: 'Telecaller', render: (row) => row.telecaller_name || '-' },
    { key: 'bd_name', header: 'BD', render: (row) => row.bd_name || '-' },
    { 
      key: 'stage_name', 
      header: 'Stage',
      render: (row) => <StatusBadge status={row.stage_name} type="stage" />
    },
    { 
      key: 'expected_value', 
      header: 'Value', 
      sortable: true,
      render: (row) => formatCurrency(row.expected_value),
      className: 'text-right'
    },
    { 
      key: 'next_followup_date', 
      header: 'Next Followup',
      render: (row) => row.next_followup_date ? formatDate(row.next_followup_date) : '-'
    },
    {
      key: 'actions',
      header: '',
      className: 'w-24',
      render: (row) => (
        <div className="flex items-center gap-1">
          <Tooltip>
            <TooltipTrigger asChild>
              <Button variant="ghost" size="icon" className="h-6 w-6">
                <Phone className="h-3 w-3" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>Log Call</TooltipContent>
          </Tooltip>
          <Tooltip>
            <TooltipTrigger asChild>
              <Button variant="ghost" size="icon" className="h-6 w-6">
                <CalendarPlus className="h-3 w-3" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>Add Followup</TooltipContent>
          </Tooltip>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="h-6 w-6">
                <MoreHorizontal className="h-3.5 w-3.5" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-32">
              {hasPermission('edit', 'leads') && (
                <DropdownMenuItem onClick={() => handleEdit(row)} className="text-xs">
                  <Pencil className="h-3 w-3 mr-2" />
                  Edit
                </DropdownMenuItem>
              )}
              {hasPermission('delete', 'leads') && (
                <DropdownMenuItem 
                  onClick={() => handleDelete(row)} 
                  className="text-xs text-destructive"
                >
                  <Trash2 className="h-3 w-3 mr-2" />
                  Delete
                </DropdownMenuItem>
              )}
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      )
    }
  ];

  const handleEdit = (lead: Lead | null) => {
    setSelectedLead(lead);
    setFormData(lead || {
      account_id: mockAccounts[0]?.account_id,
      lead_date: new Date().toISOString(),
      lead_source: 'Website',
      lead_generated_by: currentUser?.user_id || mockUsers[0].user_id,
      assigned_telecaller: null,
      bd_assigned_to: null,
      stage_id: mockLeadStages[0].stage_id,
      status_id: mockLeadStatuses[0].status_id,
      last_call_date: null,
      next_followup_date: null,
      expected_value: 0,
      products_interested: '',
      product_mapped: '',
      remarks: '',
    });
    setEditModalOpen(true);
  };

  const handleDelete = (lead: Lead) => {
    setSelectedLead(lead);
    setDeleteDialogOpen(true);
  };

  const handleSave = () => {
    if (!formData.account_id || !formData.stage_id || !formData.status_id) {
      toast({ title: 'Error', description: 'Required fields missing', variant: 'destructive' });
      return;
    }

    if (selectedLead) {
      setLeads(leads.map(l => 
        l.lead_id === selectedLead.lead_id 
          ? { ...l, ...formData, updated_date: new Date().toISOString() } as Lead
          : l
      ));
      toast({ title: 'Lead updated' });
    } else {
      const newLead: Lead = {
        ...formData as Lead,
        lead_id: Math.max(...leads.map(l => l.lead_id)) + 1,
        created_date: new Date().toISOString(),
        updated_date: new Date().toISOString(),
      };
      setLeads([...leads, newLead]);
      toast({ title: 'Lead created' });
    }
    setEditModalOpen(false);
  };

  const handleConfirmDelete = () => {
    if (selectedLead) {
      setLeads(leads.filter(l => l.lead_id !== selectedLead.lead_id));
      toast({ title: 'Lead deleted' });
    }
    setDeleteDialogOpen(false);
  };

  const handleExport = () => {
    const csv = [
      ['ID', 'Date', 'Account', 'Source', 'Stage', 'Value', 'Next Followup'].join(','),
      ...filteredData.map(l => [
        l.lead_id,
        formatDate(l.lead_date),
        `"${l.account_name}"`,
        l.lead_source,
        l.stage_name,
        l.expected_value,
        l.next_followup_date || ''
      ].join(','))
    ].join('\n');
    
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'leads.csv';
    link.click();
    toast({ title: 'Export complete' });
  };

  return (
    <AppLayout>
      <div className="space-y-4 animate-fade-in">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-xl font-semibold text-foreground">Leads</h1>
            <p className="text-sm text-muted-foreground">Track and manage your sales leads</p>
          </div>
          {hasPermission('create', 'leads') && (
            <Button size="sm" className="h-8 text-xs" onClick={() => handleEdit(null)}>
              <Plus className="h-3.5 w-3.5 mr-1.5" />
              Add Lead
            </Button>
          )}
        </div>

        {/* Filters */}
        <div className="flex gap-2 flex-wrap">
          <Select value={stageFilter} onValueChange={setStageFilter}>
            <SelectTrigger className="w-32 h-8 text-xs">
              <SelectValue placeholder="Stage" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Stages</SelectItem>
              {mockLeadStages.map(s => (
                <SelectItem key={s.stage_id} value={String(s.stage_id)}>{s.stage_name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={sourceFilter} onValueChange={setSourceFilter}>
            <SelectTrigger className="w-32 h-8 text-xs">
              <SelectValue placeholder="Source" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Sources</SelectItem>
              {leadSources.map(s => (
                <SelectItem key={s} value={s}>{s}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <DataTable
          data={paginatedData}
          columns={columns}
          total={filteredData.length}
          page={page}
          limit={limit}
          onPageChange={setPage}
          onSearch={setSearch}
          onSort={(key, dir) => { setSortKey(key); setSortDirection(dir); }}
          sortKey={sortKey}
          sortDirection={sortDirection}
          onExport={handleExport}
          selectable
          selectedIds={selectedIds}
          onSelectionChange={setSelectedIds}
          idKey="lead_id"
          emptyMessage="No leads found. Add your first lead!"
        />

        {/* Edit Modal */}
        <CompactModal
          open={editModalOpen}
          onOpenChange={setEditModalOpen}
          title={selectedLead ? 'Edit Lead' : 'Add Lead'}
          size="lg"
        >
          <div className="grid grid-cols-2 gap-3 max-h-[60vh] overflow-y-auto pr-1">
            <div>
              <Label className="text-xs">Account *</Label>
              <Select 
                value={String(formData.account_id || '')} 
                onValueChange={v => setFormData({ ...formData, account_id: Number(v) })}
              >
                <SelectTrigger className="h-8 text-sm mt-1">
                  <SelectValue placeholder="Select account" />
                </SelectTrigger>
                <SelectContent>
                  {mockAccounts.map(a => (
                    <SelectItem key={a.account_id} value={String(a.account_id)}>
                      {a.account_name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Lead Source *</Label>
              <Select 
                value={formData.lead_source || ''} 
                onValueChange={v => setFormData({ ...formData, lead_source: v as LeadSource })}
              >
                <SelectTrigger className="h-8 text-sm mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {leadSources.map(s => (
                    <SelectItem key={s} value={s}>{s}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Lead Date</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="w-full h-8 text-sm mt-1 justify-start font-normal">
                    {formData.lead_date ? format(new Date(formData.lead_date), 'dd-MM-yyyy') : 'Pick date'}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={formData.lead_date ? new Date(formData.lead_date) : undefined}
                    onSelect={(d) => setFormData({ ...formData, lead_date: d?.toISOString() || '' })}
                    className="pointer-events-auto"
                  />
                </PopoverContent>
              </Popover>
            </div>
            <div>
              <Label className="text-xs">Generated By</Label>
              <Select 
                value={String(formData.lead_generated_by || '')} 
                onValueChange={v => setFormData({ ...formData, lead_generated_by: Number(v) })}
              >
                <SelectTrigger className="h-8 text-sm mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {mockUsers.map(u => (
                    <SelectItem key={u.user_id} value={String(u.user_id)}>{u.full_name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Assigned Telecaller</Label>
              <Select 
                value={String(formData.assigned_telecaller || 'none')} 
                onValueChange={v => setFormData({ ...formData, assigned_telecaller: v === 'none' ? null : Number(v) })}
              >
                <SelectTrigger className="h-8 text-sm mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">None</SelectItem>
                  {mockUsers.filter(u => u.role === 'Telecaller').map(u => (
                    <SelectItem key={u.user_id} value={String(u.user_id)}>{u.full_name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">BD Assigned To</Label>
              <Select 
                value={String(formData.bd_assigned_to || 'none')} 
                onValueChange={v => setFormData({ ...formData, bd_assigned_to: v === 'none' ? null : Number(v) })}
              >
                <SelectTrigger className="h-8 text-sm mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">None</SelectItem>
                  {mockUsers.filter(u => u.role === 'BD').map(u => (
                    <SelectItem key={u.user_id} value={String(u.user_id)}>{u.full_name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Stage *</Label>
              <Select 
                value={String(formData.stage_id || '')} 
                onValueChange={v => {
                  const stageId = Number(v);
                  const firstStatus = mockLeadStatuses.find(s => s.stage_id === stageId);
                  setFormData({ 
                    ...formData, 
                    stage_id: stageId,
                    status_id: firstStatus?.status_id || formData.status_id
                  });
                }}
              >
                <SelectTrigger className="h-8 text-sm mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {mockLeadStages.map(s => (
                    <SelectItem key={s.stage_id} value={String(s.stage_id)}>{s.stage_name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Status *</Label>
              <Select 
                value={String(formData.status_id || '')} 
                onValueChange={v => setFormData({ ...formData, status_id: Number(v) })}
              >
                <SelectTrigger className="h-8 text-sm mt-1">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {statusesForStage.map(s => (
                    <SelectItem key={s.status_id} value={String(s.status_id)}>{s.status_name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">Last Call Date</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="w-full h-8 text-sm mt-1 justify-start font-normal">
                    {formData.last_call_date ? format(new Date(formData.last_call_date), 'dd-MM-yyyy') : 'Pick date'}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={formData.last_call_date ? new Date(formData.last_call_date) : undefined}
                    onSelect={(d) => setFormData({ ...formData, last_call_date: d?.toISOString() || null })}
                    className="pointer-events-auto"
                  />
                </PopoverContent>
              </Popover>
            </div>
            <div>
              <Label className="text-xs">Next Followup</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button variant="outline" className="w-full h-8 text-sm mt-1 justify-start font-normal">
                    {formData.next_followup_date ? format(new Date(formData.next_followup_date), 'dd-MM-yyyy') : 'Pick date'}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={formData.next_followup_date ? new Date(formData.next_followup_date) : undefined}
                    onSelect={(d) => setFormData({ ...formData, next_followup_date: d?.toISOString() || null })}
                    className="pointer-events-auto"
                  />
                </PopoverContent>
              </Popover>
            </div>
            <div>
              <Label className="text-xs">Expected Value ($)</Label>
              <Input 
                type="number"
                min="0"
                value={formData.expected_value || ''} 
                onChange={e => setFormData({ ...formData, expected_value: Number(e.target.value) || 0 })}
                className="h-8 text-sm mt-1"
              />
            </div>
            <div>
              <Label className="text-xs">Product Mapped</Label>
              <Input 
                value={formData.product_mapped || ''} 
                onChange={e => setFormData({ ...formData, product_mapped: e.target.value })}
                className="h-8 text-sm mt-1"
              />
            </div>
            <div className="col-span-2">
              <Label className="text-xs">Products Interested</Label>
              <Input 
                value={formData.products_interested || ''} 
                onChange={e => setFormData({ ...formData, products_interested: e.target.value })}
                className="h-8 text-sm mt-1"
                placeholder="e.g., Product A, Product B"
              />
            </div>
            <div className="col-span-2">
              <Label className="text-xs">Remarks</Label>
              <Textarea 
                value={formData.remarks || ''} 
                onChange={e => setFormData({ ...formData, remarks: e.target.value })}
                className="text-sm mt-1 h-16 resize-none"
              />
            </div>
          </div>
          <div className="flex justify-end gap-2 mt-4 pt-3 border-t">
            <Button variant="outline" size="sm" onClick={() => setEditModalOpen(false)}>
              Cancel
            </Button>
            <Button size="sm" onClick={handleSave}>
              {selectedLead ? 'Update' : 'Create'}
            </Button>
          </div>
        </CompactModal>

        {/* Delete Confirmation */}
        <ConfirmDialog
          open={deleteDialogOpen}
          onOpenChange={setDeleteDialogOpen}
          title="Delete Lead"
          description="Are you sure you want to delete this lead? This action cannot be undone."
          confirmLabel="Delete"
          onConfirm={handleConfirmDelete}
          variant="destructive"
        />
      </div>
    </AppLayout>
  );
}
